name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Version (e.g. 2.2.0)"
        type: string
        required: false
      patchLevel:
        description: "Select version increment/bump level"
        type: choice
        required: false
        options:
          - semver
          - patch
          - minor
        default: semver

jobs:
  release_semver:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/v2'
    steps:
      - name: "Configure GitHub Access"
        env:
          ACCESS_TOKEN: "${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}"
        run: |
          git config --global url."https://${ACCESS_TOKEN}@github.com".insteadOf "https://github.com"
          git config --global user.email "meplato-robot@users.noreply.github.com"
          git config --global user.name "meplato-robot"

      # The actions/checkout action with fetch-depth: 0 fetch all tags along with the commit history.
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: "https://npm.pkg.github.com"

      - name: "Check & Update Semantic Version"
        shell: bash
        env:
          BUMP_LEVEL: "${{ github.event.inputs.patchLevel }}"
          INPUT_VERSION: "${{ github.event.inputs.semver }}"
        run: deploy/release-ci.sh

      - name: "Publish Package"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DIST_PATH: ${{ github.workspace }}/dist
        run: |
          npm install
          npm run build
          cp package.json $DIST_PATH
          cp LICENSE $DIST_PATH
          cp README.md $DIST_PATH
          cd $DIST_PATH
          HUSKY=0 npm publish $DIST_PATH
          # TO create a ZIP archive named package.zip from the contents of the current directory 
          zip -r package.zip ./* 
          # This command will zip all the files/folder in current directory

      - name: "Release Package"
        # Alternative github action for releasing package
        # For straightforward release process and want a simple setup, softprops/action-gh-release is sufficient.
        # If need advanced release features, such as version bumping, changelog generation, and comprehensive release notes handling, ncipollo/release-action is good.
        uses: ncipollo/release-action@v1
        with:
          files: ${{ github.workspace }}/dist/package.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          # Specifying the tag name for the release based on the commit tag.
          tag: ${{ env.COMMIT_TAG }}
          generateReleaseNotes: true
