name: Release

on:
  workflow_dispatch:
    inputs:
      semversion:
        description: "Version (e.g. v2.0.7 | 2.2.0-rc1)"
        type: string
        required: false
      patchLevel:
        description: "Select version increment/bump level"
        type: choice
        required: false
        options:
          - semver
          - patch
          - minor
        default: semver
  
jobs:
  release_semver:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'    
    steps:

      - name: "Configure GitHub Access"
        env:
          ACCESS_TOKEN: "${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}"
        run: |
          git config --global url."https://${ACCESS_TOKEN}@github.com".insteadOf "https://github.com"
          git config --global user.email "meplato-robot@users.noreply.github.com"
          git config --global user.name "meplato-robot"
          
    # The actions/checkout action with fetch-depth: 0 fetch all tags along with the commit history.
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
             
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: "https://npm.pkg.github.com"
    
      - name: "Check & Update Semantic Version"
        shell: bash
        env:
          BUMP_LEVEL: "${{ github.event.inputs.patchLevel }}"
          INPUT_VERSION: "${{ github.event.inputs.semversion }}"
        run: |
          chmod +x deploy/deploy-ci.sh
          deploy/deploy-ci.sh
      - name: "Publish Package"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DIST_PATH: ${{ github.workspace }}/dist 
        run: |
          cp package.json $DIST_PATH
          cp LICENSE $DIST_PATH
          cp README.md $DIST_PATH
          cd $DIST_PATH
       
      - name: "Create GitHub Release"
        uses: ncipollo/release-action@v1
        with:
          tag: test
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
